# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: myrootpass
          MYSQL_DATABASE: funny_cats_api_test
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypass
        ports:
          - "3306"
    strategy:
      matrix:
        ruby-version: ['3.1.2']

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v2

      - name: Setup
        shell: bash
        run: |
          sudo gem install bundler
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
          bundle install
          rails active_storage:install

      - name: Setup Database
        shell: bash
        run: |
          # データベースの作成
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          RAILS_ENV: test

      - name: Run rubocop
        run: |
          bundle exec rubocop

      - name: Run tests
        shell: bash
        run: |
          bundle exec rspec
        env:
          RAILS_ENV: test
