# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 50002:3306
        env:
          MYSQL_ROOT_PASSWORD: myrootpass
          MYSQL_DATABASE: funny_cats_api_development
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypass
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
    - uses: actions/checkout@v3
    - name: Setup docker
      shell: bash
      run: |
        # イメージのビルド
        docker-compose build

        # データベースの作成
        docker-compose run web rake db:create
        docker-compose run web rake db:migrate
      env:
        RAILS_ENV: test

    - name: Run tests
      shell: bash
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec
      env:
        RAILS_ENV: test